// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6nV4t6c7k9OtlBQC6EsunH47wYAjiAdo',
    appId: '1:289490264231:web:9cb4ef123fb7b826bdfb82',
    messagingSenderId: '289490264231',
    projectId: 'fir-masterclass2',
    authDomain: 'fir-masterclass2.firebaseapp.com',
    storageBucket: 'fir-masterclass2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqM7V9SmLPF-tjEIDE9ZGnci-iEaxA20A',
    appId: '1:289490264231:android:bce318e0c71463debdfb82',
    messagingSenderId: '289490264231',
    projectId: 'fir-masterclass2',
    storageBucket: 'fir-masterclass2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2C2BVXZeKhFZo_8hm-oaOoRjQyKyyng8',
    appId: '1:289490264231:ios:ff33e705f69f253fbdfb82',
    messagingSenderId: '289490264231',
    projectId: 'fir-masterclass2',
    storageBucket: 'fir-masterclass2.appspot.com',
    iosBundleId: 'com.example.firebaseMasterclass2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2C2BVXZeKhFZo_8hm-oaOoRjQyKyyng8',
    appId: '1:289490264231:ios:2925011263056155bdfb82',
    messagingSenderId: '289490264231',
    projectId: 'fir-masterclass2',
    storageBucket: 'fir-masterclass2.appspot.com',
    iosBundleId: 'com.example.firebaseMasterclass2.RunnerTests',
  );
}
