// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvu9m8V0kZbGr6sjY6Epq4l7bBO_GHOlY',
    appId: '1:684149479476:web:2db97010b1583936c15261',
    messagingSenderId: '684149479476',
    projectId: 'fir-test-7411f',
    authDomain: 'fir-test-7411f.firebaseapp.com',
    storageBucket: 'fir-test-7411f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeR5z3DcxPlbD7e9ERH1q2bJSleWTrPoo',
    appId: '1:684149479476:android:357c6fd12c193b4bc15261',
    messagingSenderId: '684149479476',
    projectId: 'fir-test-7411f',
    storageBucket: 'fir-test-7411f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBogQalHbnnUXKfikGB-Bmaf5_t_Wpm5m4',
    appId: '1:684149479476:ios:c45b168628fd607cc15261',
    messagingSenderId: '684149479476',
    projectId: 'fir-test-7411f',
    storageBucket: 'fir-test-7411f.appspot.com',
    iosBundleId: 'com.example.backend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBogQalHbnnUXKfikGB-Bmaf5_t_Wpm5m4',
    appId: '1:684149479476:ios:c951ec127103cc19c15261',
    messagingSenderId: '684149479476',
    projectId: 'fir-test-7411f',
    storageBucket: 'fir-test-7411f.appspot.com',
    iosBundleId: 'com.example.backend.RunnerTests',
  );
}
